### ISSUE TITLE
APIs needed for demo

### ISSUE THREAD

**Issue by sreejithuvt** [DEX-Company/surfer#15]
- [x] Display all current listings in the marketplace
- [x] Display metadata for a specified listing
- [x] Submit metadata and creating a new asset ID
- [x] Create listing on the marketplace
- [x] Listing "My Asset" API based on User ID - #14
- [x] Listing "My Purchases" API based on User ID - #16
- [ ] Category wise sorting of listings - #18
- [x] Publish and unpublish button integration - #19
